var annotated_dup =
[
    [ "cpptkinter", "namespacecpptkinter.html", [
      [ "_cpptkinter", "namespacecpptkinter_1_1__cpptkinter.html", [
        [ "CommandEvent", "structcpptkinter_1_1__cpptkinter_1_1CommandEvent.html", "structcpptkinter_1_1__cpptkinter_1_1CommandEvent" ],
        [ "PythonCmd_ClientData", "structcpptkinter_1_1__cpptkinter_1_1PythonCmd__ClientData.html", "structcpptkinter_1_1__cpptkinter_1_1PythonCmd__ClientData" ],
        [ "Tcl_Obj", "classcpptkinter_1_1__cpptkinter_1_1Tcl__Obj.html", "classcpptkinter_1_1__cpptkinter_1_1Tcl__Obj" ],
        [ "TclError", "structcpptkinter_1_1__cpptkinter_1_1TclError.html", null ],
        [ "tk_window_type", "structcpptkinter_1_1__cpptkinter_1_1tk__window__type.html", "structcpptkinter_1_1__cpptkinter_1_1tk__window__type" ],
        [ "TkappObject", "structcpptkinter_1_1__cpptkinter_1_1TkappObject.html", "structcpptkinter_1_1__cpptkinter_1_1TkappObject" ]
      ] ],
      [ "cnfs", "namespacecpptkinter_1_1cnfs.html", [
        [ "BitmapImage", "structcpptkinter_1_1cnfs_1_1BitmapImage.html", "structcpptkinter_1_1cnfs_1_1BitmapImage" ],
        [ "Button", "structcpptkinter_1_1cnfs_1_1Button.html", "structcpptkinter_1_1cnfs_1_1Button" ],
        [ "Canvas", "structcpptkinter_1_1cnfs_1_1Canvas.html", "structcpptkinter_1_1cnfs_1_1Canvas" ],
        [ "Canvas_create_arc", "structcpptkinter_1_1cnfs_1_1Canvas__create__arc.html", null ],
        [ "Canvas_create_bitmap", "structcpptkinter_1_1cnfs_1_1Canvas__create__bitmap.html", null ],
        [ "Canvas_create_image", "structcpptkinter_1_1cnfs_1_1Canvas__create__image.html", null ],
        [ "Canvas_create_line", "structcpptkinter_1_1cnfs_1_1Canvas__create__line.html", null ],
        [ "Canvas_create_oval", "structcpptkinter_1_1cnfs_1_1Canvas__create__oval.html", null ],
        [ "Canvas_create_polygon", "structcpptkinter_1_1cnfs_1_1Canvas__create__polygon.html", null ],
        [ "Canvas_create_rectangle", "structcpptkinter_1_1cnfs_1_1Canvas__create__rectangle.html", null ],
        [ "Canvas_create_text", "structcpptkinter_1_1cnfs_1_1Canvas__create__text.html", null ],
        [ "Canvas_create_window", "structcpptkinter_1_1cnfs_1_1Canvas__create__window.html", "structcpptkinter_1_1cnfs_1_1Canvas__create__window" ],
        [ "Checkbutton", "structcpptkinter_1_1cnfs_1_1Checkbutton.html", "structcpptkinter_1_1cnfs_1_1Checkbutton" ],
        [ "Entry", "structcpptkinter_1_1cnfs_1_1Entry.html", "structcpptkinter_1_1cnfs_1_1Entry" ],
        [ "Frame", "structcpptkinter_1_1cnfs_1_1Frame.html", "structcpptkinter_1_1cnfs_1_1Frame" ],
        [ "grid_bbox", "structcpptkinter_1_1cnfs_1_1grid__bbox.html", "structcpptkinter_1_1cnfs_1_1grid__bbox" ],
        [ "grid_column_row_configure", "structcpptkinter_1_1cnfs_1_1grid__column__row__configure.html", "structcpptkinter_1_1cnfs_1_1grid__column__row__configure" ],
        [ "grid_configure", "structcpptkinter_1_1cnfs_1_1grid__configure.html", "structcpptkinter_1_1cnfs_1_1grid__configure" ],
        [ "is_cnf_member_trait", "structcpptkinter_1_1cnfs_1_1is__cnf__member__trait.html", null ],
        [ "is_cnf_member_trait< std::optional< T > >", "structcpptkinter_1_1cnfs_1_1is__cnf__member__trait_3_01std_1_1optional_3_01T_01_4_01_4.html", null ],
        [ "is_cnf_member_trait< std::variant< Args... > >", "structcpptkinter_1_1cnfs_1_1is__cnf__member__trait_3_01std_1_1variant_3_01Args_8_8_8_01_4_01_4.html", null ],
        [ "is_cnf_trait", "structcpptkinter_1_1cnfs_1_1is__cnf__trait.html", null ],
        [ "is_cnf_trait< T, std::integer_sequence< std::size_t, I... > >", "structcpptkinter_1_1cnfs_1_1is__cnf__trait_3_01T_00_01std_1_1integer__sequence_3_01std_1_1size__t_00_01I_8_8_8_01_4_01_4.html", null ],
        [ "Label", "structcpptkinter_1_1cnfs_1_1Label.html", "structcpptkinter_1_1cnfs_1_1Label" ],
        [ "LabelFrame", "structcpptkinter_1_1cnfs_1_1LabelFrame.html", "structcpptkinter_1_1cnfs_1_1LabelFrame" ],
        [ "Listbox", "structcpptkinter_1_1cnfs_1_1Listbox.html", "structcpptkinter_1_1cnfs_1_1Listbox" ],
        [ "Listbox_itemconfigure", "structcpptkinter_1_1cnfs_1_1Listbox__itemconfigure.html", "structcpptkinter_1_1cnfs_1_1Listbox__itemconfigure" ],
        [ "Menu", "structcpptkinter_1_1cnfs_1_1Menu.html", "structcpptkinter_1_1cnfs_1_1Menu" ],
        [ "Menu_add_cascade", "structcpptkinter_1_1cnfs_1_1Menu__add__cascade.html", "structcpptkinter_1_1cnfs_1_1Menu__add__cascade" ],
        [ "Menu_add_checkbutton", "structcpptkinter_1_1cnfs_1_1Menu__add__checkbutton.html", "structcpptkinter_1_1cnfs_1_1Menu__add__checkbutton" ],
        [ "Menu_add_command", "structcpptkinter_1_1cnfs_1_1Menu__add__command.html", "structcpptkinter_1_1cnfs_1_1Menu__add__command" ],
        [ "Menu_add_radiobutton", "structcpptkinter_1_1cnfs_1_1Menu__add__radiobutton.html", "structcpptkinter_1_1cnfs_1_1Menu__add__radiobutton" ],
        [ "Menu_add_separator", "structcpptkinter_1_1cnfs_1_1Menu__add__separator.html", "structcpptkinter_1_1cnfs_1_1Menu__add__separator" ],
        [ "Menubutton", "structcpptkinter_1_1cnfs_1_1Menubutton.html", "structcpptkinter_1_1cnfs_1_1Menubutton" ],
        [ "pack_configure", "structcpptkinter_1_1cnfs_1_1pack__configure.html", "structcpptkinter_1_1cnfs_1_1pack__configure" ],
        [ "PanedWindow", "structcpptkinter_1_1cnfs_1_1PanedWindow.html", "structcpptkinter_1_1cnfs_1_1PanedWindow" ],
        [ "PanedWindow_add", "structcpptkinter_1_1cnfs_1_1PanedWindow__add.html", "structcpptkinter_1_1cnfs_1_1PanedWindow__add" ],
        [ "PanedWindow_paneconfigure", "structcpptkinter_1_1cnfs_1_1PanedWindow__paneconfigure.html", "structcpptkinter_1_1cnfs_1_1PanedWindow__paneconfigure" ],
        [ "PhotoImage", "structcpptkinter_1_1cnfs_1_1PhotoImage.html", "structcpptkinter_1_1cnfs_1_1PhotoImage" ],
        [ "place_configure", "structcpptkinter_1_1cnfs_1_1place__configure.html", "structcpptkinter_1_1cnfs_1_1place__configure" ],
        [ "Radiobutton", "structcpptkinter_1_1cnfs_1_1Radiobutton.html", "structcpptkinter_1_1cnfs_1_1Radiobutton" ],
        [ "Scale", "structcpptkinter_1_1cnfs_1_1Scale.html", "structcpptkinter_1_1cnfs_1_1Scale" ],
        [ "Scrollbar", "structcpptkinter_1_1cnfs_1_1Scrollbar.html", "structcpptkinter_1_1cnfs_1_1Scrollbar" ],
        [ "Spinbox", "structcpptkinter_1_1cnfs_1_1Spinbox.html", "structcpptkinter_1_1cnfs_1_1Spinbox" ],
        [ "Text", "structcpptkinter_1_1cnfs_1_1Text.html", "structcpptkinter_1_1cnfs_1_1Text" ],
        [ "Text_dump", "structcpptkinter_1_1cnfs_1_1Text__dump.html", "structcpptkinter_1_1cnfs_1_1Text__dump" ],
        [ "Text_image_create", "structcpptkinter_1_1cnfs_1_1Text__image__create.html", "structcpptkinter_1_1cnfs_1_1Text__image__create" ],
        [ "Text_peer_create", "structcpptkinter_1_1cnfs_1_1Text__peer__create.html", "structcpptkinter_1_1cnfs_1_1Text__peer__create" ],
        [ "Text_search", "structcpptkinter_1_1cnfs_1_1Text__search.html", "structcpptkinter_1_1cnfs_1_1Text__search" ],
        [ "Text_tag_configure", "structcpptkinter_1_1cnfs_1_1Text__tag__configure.html", "structcpptkinter_1_1cnfs_1_1Text__tag__configure" ],
        [ "Text_window_create", "structcpptkinter_1_1cnfs_1_1Text__window__create.html", "structcpptkinter_1_1cnfs_1_1Text__window__create" ],
        [ "Toplevel", "structcpptkinter_1_1cnfs_1_1Toplevel.html", "structcpptkinter_1_1cnfs_1_1Toplevel" ],
        [ "Variable", "structcpptkinter_1_1cnfs_1_1Variable.html", "structcpptkinter_1_1cnfs_1_1Variable" ]
      ] ],
      [ "detail", "namespacecpptkinter_1_1detail.html", [
        [ "_setit", "structcpptkinter_1_1detail_1_1__setit.html", "structcpptkinter_1_1detail_1_1__setit" ],
        [ "AsObjFunctorType", "structcpptkinter_1_1detail_1_1AsObjFunctorType.html", "structcpptkinter_1_1detail_1_1AsObjFunctorType" ],
        [ "AsObjImplTrait", "structcpptkinter_1_1detail_1_1AsObjImplTrait.html", null ],
        [ "CallWrapper", "structcpptkinter_1_1detail_1_1CallWrapper.html", "structcpptkinter_1_1detail_1_1CallWrapper" ],
        [ "enable_operator_string_formatting_impl", "structcpptkinter_1_1detail_1_1enable__operator__string__formatting__impl.html", null ],
        [ "Event", "structcpptkinter_1_1detail_1_1Event.html", "structcpptkinter_1_1detail_1_1Event" ],
        [ "FromObjImplTrait", "structcpptkinter_1_1detail_1_1FromObjImplTrait.html", null ],
        [ "grid_column_row_configure_return", "structcpptkinter_1_1detail_1_1grid__column__row__configure__return.html", "structcpptkinter_1_1detail_1_1grid__column__row__configure__return" ],
        [ "GridInfo", "structcpptkinter_1_1detail_1_1GridInfo.html", "structcpptkinter_1_1detail_1_1GridInfo" ],
        [ "ignore", "structcpptkinter_1_1detail_1_1ignore.html", null ],
        [ "is_std_array", "structcpptkinter_1_1detail_1_1is__std__array.html", null ],
        [ "is_std_array< std::array< T, N > >", "structcpptkinter_1_1detail_1_1is__std__array_3_01std_1_1array_3_01T_00_01N_01_4_01_4.html", null ],
        [ "PackInfo", "structcpptkinter_1_1detail_1_1PackInfo.html", "structcpptkinter_1_1detail_1_1PackInfo" ],
        [ "PlaceInfo", "structcpptkinter_1_1detail_1_1PlaceInfo.html", "structcpptkinter_1_1detail_1_1PlaceInfo" ],
        [ "set_get_proxy", "structcpptkinter_1_1detail_1_1set__get__proxy.html", "structcpptkinter_1_1detail_1_1set__get__proxy" ],
        [ "TclBaseEvent", "structcpptkinter_1_1detail_1_1TclBaseEvent.html", "structcpptkinter_1_1detail_1_1TclBaseEvent" ],
        [ "Tk_impl", "structcpptkinter_1_1detail_1_1Tk__impl.html", "structcpptkinter_1_1detail_1_1Tk__impl" ],
        [ "TkappObjectImpl", "structcpptkinter_1_1detail_1_1TkappObjectImpl.html", "structcpptkinter_1_1detail_1_1TkappObjectImpl" ],
        [ "union_arg_overload", "structcpptkinter_1_1detail_1_1union__arg__overload.html", null ],
        [ "union_arg_overload_base", "structcpptkinter_1_1detail_1_1union__arg__overload__base.html", null ],
        [ "widget_friend", "structcpptkinter_1_1detail_1_1widget__friend.html", "structcpptkinter_1_1detail_1_1widget__friend" ]
      ] ],
      [ "utility", "namespacecpptkinter_1_1utility.html", [
        [ "enable_operator_string_formatting", "structcpptkinter_1_1utility_1_1enable__operator__string__formatting.html", null ],
        [ "extend_variants", "structcpptkinter_1_1utility_1_1extend__variants.html", null ],
        [ "extend_variants< std::variant< VArgs... >, Args... >", "structcpptkinter_1_1utility_1_1extend__variants_3_01std_1_1variant_3_01VArgs_8_8_8_01_4_00_01Args_8_8_8_01_4.html", "structcpptkinter_1_1utility_1_1extend__variants_3_01std_1_1variant_3_01VArgs_8_8_8_01_4_00_01Args_8_8_8_01_4" ],
        [ "member_functor", "classcpptkinter_1_1utility_1_1member__functor.html", "classcpptkinter_1_1utility_1_1member__functor" ],
        [ "optional_inverse_mutex_adaptor", "classcpptkinter_1_1utility_1_1optional__inverse__mutex__adaptor.html", "classcpptkinter_1_1utility_1_1optional__inverse__mutex__adaptor" ],
        [ "optional_mutex_adaptor", "classcpptkinter_1_1utility_1_1optional__mutex__adaptor.html", "classcpptkinter_1_1utility_1_1optional__mutex__adaptor" ],
        [ "reference_variant", "structcpptkinter_1_1utility_1_1reference__variant.html", "structcpptkinter_1_1utility_1_1reference__variant" ],
        [ "weak", "classcpptkinter_1_1utility_1_1weak.html", "classcpptkinter_1_1utility_1_1weak" ]
      ] ],
      [ "BaseWidget", "classcpptkinter_1_1BaseWidget.html", "classcpptkinter_1_1BaseWidget" ],
      [ "BitmapImage", "structcpptkinter_1_1BitmapImage.html", "structcpptkinter_1_1BitmapImage" ],
      [ "Button", "structcpptkinter_1_1Button.html", "structcpptkinter_1_1Button" ],
      [ "Canvas", "structcpptkinter_1_1Canvas.html", "structcpptkinter_1_1Canvas" ],
      [ "Checkbutton", "structcpptkinter_1_1Checkbutton.html", "structcpptkinter_1_1Checkbutton" ],
      [ "Entry", "structcpptkinter_1_1Entry.html", "structcpptkinter_1_1Entry" ],
      [ "Frame", "structcpptkinter_1_1Frame.html", "structcpptkinter_1_1Frame" ],
      [ "Grid", "structcpptkinter_1_1Grid.html", "structcpptkinter_1_1Grid" ],
      [ "Image", "structcpptkinter_1_1Image.html", "structcpptkinter_1_1Image" ],
      [ "Label", "structcpptkinter_1_1Label.html", "structcpptkinter_1_1Label" ],
      [ "LabelFrame", "structcpptkinter_1_1LabelFrame.html", "structcpptkinter_1_1LabelFrame" ],
      [ "Listbox", "structcpptkinter_1_1Listbox.html", "structcpptkinter_1_1Listbox" ],
      [ "Menu", "structcpptkinter_1_1Menu.html", "structcpptkinter_1_1Menu" ],
      [ "Menubutton", "structcpptkinter_1_1Menubutton.html", "structcpptkinter_1_1Menubutton" ],
      [ "Misc", "classcpptkinter_1_1Misc.html", "classcpptkinter_1_1Misc" ],
      [ "OptionMenu", "classcpptkinter_1_1OptionMenu.html", "classcpptkinter_1_1OptionMenu" ],
      [ "Pack", "structcpptkinter_1_1Pack.html", "structcpptkinter_1_1Pack" ],
      [ "PanedWindow", "structcpptkinter_1_1PanedWindow.html", "structcpptkinter_1_1PanedWindow" ],
      [ "PhotoImage", "structcpptkinter_1_1PhotoImage.html", "structcpptkinter_1_1PhotoImage" ],
      [ "Place", "structcpptkinter_1_1Place.html", "structcpptkinter_1_1Place" ],
      [ "Radiobutton", "structcpptkinter_1_1Radiobutton.html", "structcpptkinter_1_1Radiobutton" ],
      [ "Scale", "structcpptkinter_1_1Scale.html", "structcpptkinter_1_1Scale" ],
      [ "Scrollbar", "structcpptkinter_1_1Scrollbar.html", "structcpptkinter_1_1Scrollbar" ],
      [ "Spinbox", "structcpptkinter_1_1Spinbox.html", "structcpptkinter_1_1Spinbox" ],
      [ "Text", "structcpptkinter_1_1Text.html", "structcpptkinter_1_1Text" ],
      [ "Tk", "classcpptkinter_1_1Tk.html", "classcpptkinter_1_1Tk" ],
      [ "Toplevel", "structcpptkinter_1_1Toplevel.html", "structcpptkinter_1_1Toplevel" ],
      [ "TypedCheckbutton", "structcpptkinter_1_1TypedCheckbutton.html", "structcpptkinter_1_1TypedCheckbutton" ],
      [ "TypedListbox", "structcpptkinter_1_1TypedListbox.html", "structcpptkinter_1_1TypedListbox" ],
      [ "TypedRadiobutton", "structcpptkinter_1_1TypedRadiobutton.html", "structcpptkinter_1_1TypedRadiobutton" ],
      [ "TypedVariable", "structcpptkinter_1_1TypedVariable.html", "structcpptkinter_1_1TypedVariable" ],
      [ "Variable", "classcpptkinter_1_1Variable.html", "classcpptkinter_1_1Variable" ],
      [ "Widget", "structcpptkinter_1_1Widget.html", "structcpptkinter_1_1Widget" ],
      [ "Wm", "structcpptkinter_1_1Wm.html", "structcpptkinter_1_1Wm" ],
      [ "XView", "structcpptkinter_1_1XView.html", "structcpptkinter_1_1XView" ],
      [ "YView", "structcpptkinter_1_1YView.html", "structcpptkinter_1_1YView" ]
    ] ],
    [ "std", null, [
      [ "formatter< T >", "structstd_1_1formatter_3_01T_01_4.html", "structstd_1_1formatter_3_01T_01_4" ]
    ] ]
];