/// @file constants.ixx
/// @brief  Implements constants.py.


export module cpptkinter:constants;
import std;
import hhh;

#define BOOL_CONSTANT(name) constexpr int name = 0
#define STRING_CONSTANT(name) const std::string name = hhh::misc::to_lower(#name)
#define STRING_CONSTANT2(name, value) const std::string name = value


export namespace cpptkinter::constants
{
	BOOL_CONSTANT(NO);
	BOOL_CONSTANT(YES);
	BOOL_CONSTANT(TRUE);
	BOOL_CONSTANT(FALSE);
	STRING_CONSTANT(ON);
	STRING_CONSTANT(OFF);
	STRING_CONSTANT(N);
	STRING_CONSTANT(S);
	STRING_CONSTANT(E);
	STRING_CONSTANT(W);
	STRING_CONSTANT(NW);
	STRING_CONSTANT(SW);
	STRING_CONSTANT(NE);
	STRING_CONSTANT(SE);
	STRING_CONSTANT(NS);
	STRING_CONSTANT(EW);
	STRING_CONSTANT(NSEW);
	STRING_CONSTANT(CENTER);
	STRING_CONSTANT(NONE);
	STRING_CONSTANT(X);
	STRING_CONSTANT(Y);
	STRING_CONSTANT(BOTH);
	STRING_CONSTANT(LEFT);
	STRING_CONSTANT(TOP);
	STRING_CONSTANT(RIGHT);
	STRING_CONSTANT(BOTTOM);
	STRING_CONSTANT(RAISED);
	STRING_CONSTANT(SUNKEN);
	STRING_CONSTANT(FLAT);
	STRING_CONSTANT(RIDGE);
	STRING_CONSTANT(GROOVE);
	STRING_CONSTANT(SOLID);
	STRING_CONSTANT(HORIZONTAL);
	STRING_CONSTANT(VERTICAL);
	STRING_CONSTANT(NUMERIC);
	STRING_CONSTANT(CHAR);
	STRING_CONSTANT(WORD);
	STRING_CONSTANT(BASELINE);
	STRING_CONSTANT(INSIDE);
	STRING_CONSTANT(OUTSIDE);
	STRING_CONSTANT(SEL);
	STRING_CONSTANT2(SEL_FIRST, "sel.first");
	STRING_CONSTANT2(SEL_LAST, "sel.last");
	STRING_CONSTANT(END);
	STRING_CONSTANT(INSERT);
	STRING_CONSTANT(CURRENT);
	STRING_CONSTANT(ANCHOR);
	STRING_CONSTANT(ALL);
	STRING_CONSTANT(NORMAL);
	STRING_CONSTANT(DISABLED);
	STRING_CONSTANT(ACTIVE);
	STRING_CONSTANT(HIDDEN);
	STRING_CONSTANT(CASCADE);
	STRING_CONSTANT(CHECKBUTTON);
	STRING_CONSTANT(COMMAND);
	STRING_CONSTANT(RADIOBUTTON);
	STRING_CONSTANT(SEPARATOR);
	STRING_CONSTANT(SINGLE);
	STRING_CONSTANT(BROWSE);
	STRING_CONSTANT(MULTIPLE);
	STRING_CONSTANT(EXTENDED);
	STRING_CONSTANT(DOTBOX);
	STRING_CONSTANT(UNDERLINE);
	STRING_CONSTANT(PIESLICE);
	STRING_CONSTANT(CHORD);
	STRING_CONSTANT(ARC);
	STRING_CONSTANT(FIRST);
	STRING_CONSTANT(LAST);
	STRING_CONSTANT(BUTT);
	STRING_CONSTANT(PROJECTING);
	STRING_CONSTANT(ROUND);
	STRING_CONSTANT(BEVEL);
	STRING_CONSTANT(MITER);
	STRING_CONSTANT(MOVETO);
	STRING_CONSTANT(SCROLL);
	STRING_CONSTANT(UNITS);
	STRING_CONSTANT(PAGES);
}

//#undef BOOL_CONSTANT
//#undef STRING_CONSTANT
//#undef STRING_CONSTANT2
