name: Doxygen Docs

on:
  push:
    branches:
      - main  # Run when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config_file: Doxyfile