name: build and deploy doxygen docs


on:
  push:
    branches:
      - main  # Run when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Checkout your repository
      - name: Checkout
        uses: actions/checkout@v4

      # Install Doxygen
      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      # Build documentation
      - name: Build Doxygen documentation
        run: doxygen Doxyfile

      # Upload website to GitHub Pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
